"""Contract / Dockerfile / devcontainer generation (all marked, never guaranteed)."""

from __future__ import annotations

from ghostdeps.models import ScanResult

HEADER = "# GENERATED FROM OBSERVED EVIDENCE — NOT YET VERIFIED. Review before use."


def generate_contract(result: ScanResult) -> str:
    runtimes = sorted({d.name for d in result.dependencies if d.type == "RUNTIME"})
    system = sorted(
        {
            d.name
            for d in result.dependencies
            if d.type == "SYSTEM_BINARY" and d.name != "dynamic-subprocess"
        }
    )
    syspkgs = sorted({d.name for d in result.dependencies if d.type == "SYSTEM_PACKAGE"})
    services = sorted({d.name for d in result.dependencies if d.type == "SERVICE"})
    env_req = sorted(
        {
            d.name
            for d in result.dependencies
            if d.type in ("ENVIRONMENT_VARIABLE", "CREDENTIAL_REFERENCE")
            and d.confidence in ("SUPPORTED", "STRONG", "VERIFIED")
        }
    )
    nets = sorted({d.name for d in result.dependencies if d.type == "NETWORK_ENDPOINT"})[:20]
    L = [HEADER, "# ghostdeps contract v1", ""]
    L.append("runtime:")
    if runtimes:
        for r in runtimes:
            L.append(f'  {r}: "any  # provenance: see ghostdeps scan evidence"')
    else:
        L.append('  unknown: "no runtime evidence found"')
    L.append("")
    L.append("system:")
    for s in system:
        prov = _prov(result, s)
        L.append(f"  - {s}  # {prov}")
    if not system:
        L.append("  []")
    L.append("")
    L.append("system_packages:")
    for s in syspkgs:
        L.append(f"  - {s}")
    if not syspkgs:
        L.append("  []")
    L.append("")
    L.append("services:")
    for s in services:
        L.append(f"  {s.lower().replace(' ', '_').replace('-', '_')}:")
        L.append('    version: "any  # inferred, not proven"')
    if not services:
        L.append("  {}")
    L.append("")
    L.append("environment:")
    L.append("  required:")
    for e in env_req:
        L.append(f"    - {e}")
    if not env_req:
        L.append("    []")
    L.append("")
    L.append("network:")
    for n in nets:
        L.append(f"  - {n}")
    if not nets:
        L.append("  []")
    L.append("")
    L.append("platform:")
    L.append("  os:")
    L.append("    - linux  # default assumption; verify with `ghostdeps portable`")
    L.append("")
    return "\n".join(L)


def generate_docker(result: ScanResult) -> str:
    L = [
        HEADER,
        "# Review every line. This file was generated, not verified.",
        "",
        "FROM python:3.12-slim",
        "",
    ]
    syspkgs = sorted(
        {
            d.name
            for d in result.dependencies
            if d.type == "SYSTEM_PACKAGE" and not d.name.startswith("pip:") and "(ci)" not in d.name
        }
    )
    if syspkgs:
        L.append("RUN apt-get update \\")
        L.append("    && apt-get install -y --no-install-recommends \\")
        for p in syspkgs[:20]:
            L.append(f"        {p} \\")
        L.append("    && rm -rf /var/lib/apt/lists/*")
        L.append("")
    else:
        L.append("# No system packages detected. Add any ghost SYSTEM_PACKAGE findings here.")
        L.append("")
    L.append("WORKDIR /app")
    L.append("COPY . /app")
    L.append("")
    L.append('CMD ["sh", "-c", "echo Review generated Dockerfile before use; exit 1"]')
    L.append("")
    return "\n".join(L)


def generate_devcontainer(result: ScanResult) -> str:
    import json

    env = sorted(
        {
            d.name
            for d in result.dependencies
            if d.type in ("ENVIRONMENT_VARIABLE", "CREDENTIAL_REFERENCE")
        }
    )[:20]
    return (
        json.dumps(
            {
                "$comment": HEADER,
                "name": "ghostdeps-generated (NOT YET VERIFIED)",
                "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
                "remoteEnv": {k: "${localEnv:" + k + "}" for k in env},
                "postCreateCommand": "echo 'Generated by ghostdeps; review before use.'",
            },
            indent=2,
        )
        + "\n"
    )


def _prov(result: ScanResult, name: str) -> str:
    for d in result.dependencies:
        if d.name == name and d.evidences:
            e = d.evidences[0]
            loc = f"{e.file}:{e.line}" if e.file else e.detector
            return f"provenance: {loc}"
    return "provenance: unknown"
